### PR TITLE
Add macro for deriving prost boilerplate

### PR DESCRIPTION
**Pull request by segeljakt**
This PR addresses #164. See `...` for comments.

### CODE REVIEW

**Comment by segeljakt** [comment]
The only caveat is that this PR pulls in `syn = { ... , features = ["full"] }`, is it OK or should we hide it behind a feature flag?

**Comment by Max-Meldrum** [comment]
> The only caveat is that this PR pulls in `syn = { ... , features = ["full"] }`, is it OK or should we hide it behind a feature flag?

If it is needed for the PR, then I think its fine. If it slows down compilation too much we can look to remove it later on.

**Comment by segeljakt** [comment]
Did I break something with Windows? 😬  @Max-Meldrum

**Comment by Max-Meldrum** [comment]
> Did I break something with Windows? 😬 @Max-Meldrum

No, windows is broken 👍

**Review by Max-Meldrum — APPROVED** [review]
Looks good 👍  Closes #164

**Pull request merged**
