### PR TITLE
Add sled- and FASTER-based state backend implementations

### PR DESCRIPTION
**Pull request by mrobakowski**
This PR adds state backend implementations based on [sled](https://github.com/spacejam/sled) and [FASTER](https://github.com/microsoft/FASTER). The recovery tests are also implemented for them. 

Sled checkpointing and recovery are implemented through full export/import for now, because sled doesn't support efficient snapshots/MVCC yet (there are plans for it afaik). 

FASTER doesn't support range scans, so map state is implemented with an additional storage entry that contains an array of all the keys related to the particular map state instance.

### CODE REVIEW

**Comment by Max-Meldrum** [comment]
Looks good! Is it ready to be merged?

**Comment by mrobakowski** [comment]
I think so :). I'm just waiting for the CI to finish.

**Comment by mrobakowski** [comment]
`test_faster_recovery_pipeline` did not pass, again. And I don't really know why, since some logs probably got swallowed :/ and I cannot reproduce this on my machine.

**Comment by mrobakowski** [comment]
Still no idea why it doesn't pass. We could just ignore this test for now...

**Comment by Max-Meldrum** [comment]
Sure, just comment it out or something.

**Pull request merged**
